### ISSUE TITLE
위키 오타 수정

### ISSUE THREAD

**Issue by developomp** [rust-kr/rust-by-example-ko#4]
[위키](https://github.com/rust-kr/rust-by-example-ko/wiki) `번역 방식` 섹션에 스타일 가이드의 영문 예 앞에 `1`이 추가되었습니다. backtick을 치는 과정에서 생긴듯 합니다.

**Comment by malkoG** [comment]
`1It cancels the selected items on the online store. 를 번역할 때,` 이거네요

**Comment by jinto** [comment]
감사합니다.
